# Production Docker Compose override
# Use this file for production deployment with optimized OPcache settings
# Run with: docker-compose -f compose.yaml -f compose.prod.yaml up -d

version: '3.8'

services:
  backend:
    environment:
      - DATABASE_URL=mysql://root:password@database:3306/jamaity?serverVersion=8.0&charset=utf8mb4
      - APP_ENV=prod
      - APP_DEBUG=0
    command: ["/bin/bash", "-c", "configure-opcache.sh && composer install --no-dev --optimize-autoloader && php bin/console cache:clear --env=prod && php bin/console cache:warmup --env=prod && (php bin/console doctrine:database:create --if-not-exists || true) && (php bin/console doctrine:migrations:migrate --no-interaction || true) && php-fpm -F"]
    volumes:
      # In production, you might want to use a more restrictive volume mapping
      - .:/var/www/html:ro  # Read-only for security
      - ./var:/var/www/html/var  # Writable cache and log directories